# ===============================

# APP NAME

# ===============================

spring.application.name=airBnbApp

# ===============================

# DATABASE (LOCAL + CLOUD SUPPORT)

# ===============================

#spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/airBnb}
spring.datasource.url=${DB_URL:}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:bhumi2605}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================

# JPA / HIBERNATE

# ===============================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================

# SERVER (IMPORTANT)

# ===============================

server.port=${PORT:8080}

# OPTIONAL (enable only if needed)

# server.servlet.context-path=/api/v1

# ===============================

# LOGGING

# ===============================

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework=INFO

# ===============================

# JWT CONFIG (LOCAL + PROD SAFE)

# ===============================

jwt.secretKey=${JWT_SECRET:bchbyw87748fjnrthv8h5uguh8hv9333unu58h5h44884bvubru48h8vscgyvtsbcy}

# ===============================

# FRONTEND URL

# ===============================

frontend.url=${FRONTEND_URL:[http://localhost:5173}](http://localhost:5173})

# ===============================

# RAZORPAY CONFIG (LOCAL + PROD SAFE)

# ===============================

razorpay.key=${RAZORPAY_KEY:rzp_test_SUL7XstcBKfgjN}
razorpay.secret=${RAZORPAY_SECRET:CXnDk0YcYFO6to39Mu3OVMha}
razorpay.webhook.secret=${RAZORPAY_WEBHOOK_SECRET:whsec_test_1234567890abcdef}


spring.datasource.initialization-mode=never