# ===============================

# APP NAME

# ===============================

spring.application.name=airBnbApp

# ===============================

# DATABASE (RAILWAY READY)

# ===============================
# ===============================
# DATABASE (RAILWAY SAFE)
# ===============================

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/airBnb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:bhumi2605}
spring.datasource.driver-class-name=org.postgresql.Driver

# Prevent crash if DB not available at startup
spring.datasource.hikari.initialization-fail-timeout=0



# Prevent DB issues during build

spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

# ===============================

# JPA / HIBERNATE

# ===============================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================

# SERVER (IMPORTANT FOR RAILWAY)

# ===============================

server.port=${PORT:8080}

# ===============================

# LAZY INIT (FIXES BUILD ERROR)

# ===============================

spring.main.lazy-initialization=true

# ===============================

# LOGGING

# ===============================

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework=INFO

# ===============================

# JWT CONFIG

# ===============================

jwt.secretKey=${JWT_SECRET:bchbyw87748fjnrthv8h5uguh8hv9333unu58h5h44884bvubru48h8vscgyvtsbcy}

# ===============================

# FRONTEND URL

# ===============================

frontend.url=${FRONTEND_URL:[http://localhost:5173}](http://localhost:5173})

# ===============================

# RAZORPAY CONFIG

# ===============================

razorpay.key=${RAZORPAY_KEY:rzp_test_SUL7XstcBKfgjN}
razorpay.secret=${RAZORPAY_SECRET:CXnDk0YcYFO6to39Mu3OVMha}
razorpay.webhook.secret=${RAZORPAY_WEBHOOK_SECRET:whsec_test_1234567890abcdef}
